version: '2'

services: 
 couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    #
    ports:
      - "5984:5984"
