
version: '2'

networks:
  byfn:

services:

  orderer.example.com:
    extends:
      file: base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - byfn

  peer0.org1.example.com:
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.org1.example.com
    container_name: peer0.org1.example.com
    depends_on:
      - orderer.example.com
    networks:
      - byfn

  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.org2.example.com
    depends_on:
      - orderer.example.com
    networks:
      - byfn

  peer0.org3.example.com:
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.org3.example.com
    container_name: peer0.org3.example.com
    depends_on:
      - orderer.example.com
    networks:
      - byfn

  peer0.org4.example.com:
    container_name: peer0.org4.example.com
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.org4.example.com
    depends_on:
      - orderer.example.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:x86_64-1.1.0
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org4.example.com:7051
      - CORE_PEER_LOCALMSPID=Org4MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    working_dir: /home
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org4.example.com/users/Admin@org4.example.com/msp:/etc/hyperledger/msp
    depends_on:
      - orderer.example.com
      - peer0.org1.example.com
    networks:
      - byfn